task_name: LiftBanana
category_name: RigidBody

tool_keypoint_name_list: [tool_head, tool_tail, tool_side]
object_keypoint_name_list: [rigidbody_object_head]

constraint_list:

- keypoint_name: tool_head
  target_keypoint_name: rigidbody_object_head
  tolerance: 0.0001
  type: point2point_constraint

# ensure gripper approaches banana with proper orientation (90 degree rotation around Z)
- axis_from_keypoint_name: tool_head
  axis_to_keypoint_name: tool_tail
  target_axis: [0.0, 0.0, 1.0]
  target_axis_frame: world
  tolerance: 0.01
  target_inner_product: 1
  type: frame_axis_parallel

# pre-actuation pose list. 
pre_actuation_motions: [["translate_z", -0.0]] # [pre-grasp: move gripper 2cm above object keypoint]

# post-actuation pose list.
post_actuation_motions: [["gripper_close", 1.0], ["translate_z", -0.2]] # [lift banana up, close gripper]

# trajectory time
actuation_time: 4 # time to reach task goal pose
pre_actuation_times: [5]
post_actuation_times: [6, 7]